spring.profiles.active: test
---
server:
  port: 8080
external:
  system:
    vehicles:
      uri: https://apidev.meep.me/tripplan/api/v1/routers/lisboa/resources
      filter: ?lowerLeftLatLon=38.711046,-9.160096&upperRightLatLon=38.739429,-9.137115&companyZoneIds=545,467,473
---
spring:
  profiles: test
  jpa:
    show_sql: false
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE;IGNORECASE=TRUE


